Techstore/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls')),
    path('account/', include('account.urls')),
    path('', include('store.urls')),
]

account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.user_login, name='user-login'),
    path('logout/', views.user_logout, name='user-logout'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='user-logout'),
    path('profile/', views.profile, name='profile'),
]

cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add-to-cart'),
    path('add-to-favourites/<int:product_id>/', views.add_to_favourites, name='add-to-favourites'),
    path('decrease-from-cart/<int:product_id>/', views.decrease_from_cart, name='cart-decrease'),
    path('remove-from-favourites/<int:product_id>/', views.remove_from_favourites, name='favourites-remove'),
    path('remove-from-cart/<int:product_id>/', views.remove_from_cart, name='cart-remove'),
    path('cart/', views.cart, name='cart_detail'),
    path('favourites/', views.favourites, name='favourites_detail'),
    path('booking/', views.booking, name='booking'),
    path('order-success/', views.order_success, name='order_success'),
    path('orders/', views.orders, name='orders'),
    path('order/<int:order_id>/', views.order, name='order_detail'),
]

store/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from Techstore import settings
from . import views
urlpatterns = [
    path('', views.index, name='index'),
    path('product/<int:product_id>/', views.product, name='product'),
    path('search-product', views.search_product, name='search_product'),
    #
    path('about/', views.about, name='about'),
    path('shipping/', views.shipping, name='shipping'),
    path('sercent/', views.sercent, name='sercent'),
    #
    path('<str:product_type>/', views.product_type, name='product_type'),
    path('brand/<str:brand_name>/', views.brands, name='brands'),
    path('send-message', views.send_message, name='send_message'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models
# Create your models here.

store/models.py
from django.db import models

from django.conf import settings

from django.contrib.auth.models import User

import cart

# Create your models here.
from django.utils import timezone


class ProductType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.IntegerField()
    stock = models.IntegerField()
    image = models.ImageField(upload_to='products/', blank=True, null=True)
    availability = models.BooleanField(default=True)
    product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE, related_name='products')
    date_added = models.DateTimeField(default=timezone.now)
    purchases = models.PositiveIntegerField(default=0)
    brand = models.ForeignKey('Brand', on_delete=models.CASCADE, related_name='products', null=True)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class ProductAttribute(models.Model):
    name = models.CharField(max_length=100)
    product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE, related_name='attributes')

    def __str__(self):
        return self.name


class ProductAttributeValue(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product_values')
    attribute = models.ForeignKey(ProductAttribute, on_delete=models.CASCADE, related_name='attribute_values')
    value = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.attribute.name}: {self.value}"


class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='cart')
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE, null=True)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Cart {self.id} for {self.user.email}"

    def __iter__(self):
        return iter(self.items.all())


class Favourites(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='favourites')
    created_at = models.DateTimeField(auto_now_add=True)


class FavouriteItem(models.Model):
    favourites_list = models.ForeignKey(Favourites, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.product.name}"

    def get_total_price(self):
        return self.quantity * self.product.price


class Order(models.Model):
    class Delivery(models.TextChoices):
        courier = 'Courier'
        pickup = 'Pickup'

    class Payment(models.TextChoices):
        card = 'Card', 'card'
        cash = 'Cash', 'cash'

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders')
    name = models.CharField(max_length=100, default='')
    address = models.CharField(max_length=100, default='')
    phone_number = models.CharField(max_length=100, default='')
    delivery_option = models.CharField(max_length=100, choices=Delivery.choices, default=Delivery.courier)
    payment_option = models.CharField(max_length=100, choices=Payment.choices, default=Payment.card)
    #above user data
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.BooleanField(default=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.id}: {self.user}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.quantity} of {self.product.name} in order {self.order.id}"

    def get_total_price(self):
        return self.quantity * self.price


class Application(models.Model):
    name = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name}: {self.phone_number}"

cart/forms.py
from django import forms
from store.models import CartItem, Cart, Order


class OrderForm(forms.ModelForm):
    address = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'del__input',
        'placeholder': 'Введите свой адрес',
    }))

    DELIVERY_CHOICES = [
        ('Pickup', 'Pickup'),
        ('Courier', 'Courier'),
    ]
    PAYMENT_CHOICES = [
        ('Card', 'CARD'),
        ('Cash', 'CASH'),
    ]
    delivery_option = forms.ChoiceField(
        choices=DELIVERY_CHOICES,
        widget=forms.RadioSelect(attrs={'class': 'block__text'})
    )
    payment_option = forms.ChoiceField(
        choices=PAYMENT_CHOICES,
        widget=forms.RadioSelect(attrs={'class': 'block__text'})
    )

    class Meta:
        model = Order
        exclude = ('user',)

store/forms.py
from django import forms
from django.contrib.auth.models import User
from store.models import Application


#now forms from account_app are used
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class UserRegistrationForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput, label='Password')
    password2 = forms.CharField(widget=forms.PasswordInput, label='Repeat Password')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data

        password = cd['password']
        password2 = cd['password2']

        if password != password2:
            raise forms.ValidationError('Passwords must match')

        return password2


class ApplicationForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form__name', 'placeholder': 'Имя'}))
    phone_number = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form__tel', 'placeholder': 'Номер телефона'}))

    class Meta:
        model = Application
        fields = ['name', 'phone_number']

cart/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from store.models import Product, Cart, CartItem, Favourites, FavouriteItem, Order, OrderItem
from django.contrib import messages
from django.http.response import HttpResponse, JsonResponse, HttpResponseRedirect
from django.core.paginator import Paginator
from .forms import OrderForm
import stripe
from django.conf import settings
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from http import HTTPStatus

stripe.api_key = settings.STRIPE_SECRET_KEY


@login_required(login_url='account:user-login')
@login_required
def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    cart, created = Cart.objects.get_or_create(user=request.user)

    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
    if not created:
        cart_item.quantity += 1
    cart_item.save()

    messages.success(request, f'Added {product.name} to your cart.')
    return redirect('cart:cart_detail')


@login_required(login_url='account:user-login')
def add_to_favourites(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    favourites, created = Favourites.objects.get_or_create(user=request.user)
    favourite_item, created = FavouriteItem.objects.get_or_create(favourites_list=favourites, product=product)
    if created:
        messages.success(request, f'Added {product.name} to your favourites.')
    else:
        messages.info(request, f'{product.name} is already in your favourites.')
    return redirect('cart:favourites_detail')


@login_required(login_url='account:user-login')
def decrease_from_cart(request, product_id):
    cart = get_object_or_404(Cart, user=request.user)
    cart_item = get_object_or_404(CartItem, cart=cart, product_id=product_id)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
        messages.success(request, f'Reduced quantity of {cart_item.product.name} in your cart.')
    else:
        cart_item.delete()
        messages.success(request, f'Removed {cart_item.product.name} from your cart.')
    return redirect('cart:cart_detail')


def remove_from_cart(request, product_id):
    user_cart = get_object_or_404(Cart, user=request.user)
    product = get_object_or_404(Product, id=product_id)

    cart_item = get_object_or_404(CartItem, cart=user_cart, product=product)
    if cart_item:
        cart_item.delete()

    return redirect('cart:cart_detail')


@login_required(login_url='account:user-login')
def remove_from_favourites(request, product_id):
    user_favourites = get_object_or_404(Favourites, user=request.user)
    favourite_item = get_object_or_404(FavouriteItem, favourites_list=user_favourites, product_id=product_id)
    favourite_item.delete()
    messages.success(request, f'Removed {favourite_item.product.name} from your favourites.')
    return redirect('cart:favourites_detail')


@login_required(login_url='account:user-login')
def cart(request):
    user_cart, created = Cart.objects.get_or_create(user=request.user)
    cart_items = user_cart.items.all()
    paginator = Paginator(cart_items, 5)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    current_page = page_obj.number
    total_pages = paginator.num_pages

    start_page = max(current_page - 1, 1)
    end_page = min(current_page + 1, total_pages)

    page_range = range(start_page, end_page + 1)

    total_price = sum(item.get_total_price() for item in cart_items)
    return render(request, 'store/cart.html',
                  {'cart_items': cart_items, 'total_price': total_price, 'page_obj': page_obj,
                   'page_range': page_range})


@login_required(login_url='account:user-login')
def favourites(request):
    print(request.user)
    user_favourites, created = Favourites.objects.get_or_create(user=request.user)
    favourite_items = user_favourites.items.all()
    return render(request, 'store/favourites.html', {'favourite_items': favourite_items})


@login_required(login_url='account:user-login')
@csrf_exempt
def booking(request):
    user_cart = Cart.objects.get(user=request.user)
    cart_items = user_cart.items.all()

    total_price = sum(item.get_total_price() for item in cart_items)

    if request.method == 'POST':
        print(request.POST)
        form = OrderForm(request.POST)
        print(form.is_valid())
        print(form.errors)
        if form.is_valid():
            name = form.cleaned_data['name']
            address = form.cleaned_data['address']
            phone_number = form.cleaned_data['phone_number']

            delivery_option = form.cleaned_data['delivery_option']
            payment_option = form.cleaned_data['payment_option']
            total_price = form.cleaned_data['total_price']

            order_instance = Order(user=request.user, name=name, address=address, phone_number=phone_number,
                                   payment_option=payment_option, delivery_option=delivery_option,
                                   total_price=total_price)

            checkout_session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                line_items=[
                    {
                        # Provide the exact Price ID (for example, pr_1234) of the product you want to sell
                        'price': 'price_1PQsnY09YDBQc1tNaSHSWLzL',
                        'quantity': 1,
                    },
                ],
                mode='payment',
                success_url=settings.DOMAIN_URL + reverse('cart:order_success'),
                cancel_url=settings.DOMAIN_URL + '/cancel.html',
            )

            order_instance.save()

            for cart_item in user_cart:
                order_item = OrderItem.objects.create(order=order_instance, product=cart_item.product,
                                                      quantity=cart_item.quantity,
                                                      price=cart_item.product.price * cart_item.quantity)
                order_item.save()

            return HttpResponseRedirect(checkout_session.url, status=HTTPStatus.SEE_OTHER)
    else:
        form = OrderForm()

    return render(request, 'store/booking.html', {'total_price': total_price, 'form': form})


def order_success(request):
    return render(request, 'store/order-success.html')


def orders(request):
    user = request.user
    user_orders = user.orders.all()
    return render(request, 'store/orders.html', {'user': user, 'user_orders': user_orders})


def order(request, order_id):
    curr_order = get_object_or_404(Order, id=order_id)
    return render(request, 'store/order.html', {'order': curr_order})

store/templates/store/brand_products.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
        <section class="proc">
            <div class="container">
                <h1>{{ brand_name }}</h1>
                <div class="proc__wrapper" style="margin: auto">
                    <div class="proc__goods" style="margin: auto">
                        {% for product in brand_products %}
                        <div class="goods__el" style="margin-inline: auto">
                            <div class="goods__white" style="width: 55%">
                                <a href="{% url 'product' product_id=product.id %}">
                                    <div class="goods__img" style="display: flex; justify-content: center; align-items: center"><img src="{{ product.image.url }}" alt="proc" style="width: 175px"></div>
                                    <div class="goods__descr">
                                        <div class="goods__name">{{ product.name}}</div>
                                        <div class="goods__wrapper">
                                            <div class="goods__param">
                                                {% for parameter in parameters.show_names %}
                                                    <div class="param">
                                                        <div class="param__cell">{{ parameter }}</div>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                            <div class="goods__data">
                                                {% for parameter in parameters.db_names %}
                                                    {% for product_value in product.product_values.all %}
                                                        {% if product_value.attribute.name == parameter %}
                                                            <div class="data__data">{{ product_value.value }}</div>
                                                        {% endif %}
                                                    {% endfor %}
                                                {% endfor %}
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                            <div class="goods__blue" style="width: 45%">
                                <div class="blue__chosen">
                                    <form action="{% url 'cart:add-to-favourites' product.id %}" method="POST">
                                        {% csrf_token %}
                                        <button><img src="{% static 'icons/proc/Vector_4.svg' %}" alt="like"></button>
                                    </form>
                                </div>
                                <div class="blue__avail">
                                    ✓  В наличии
                                </div>
                                <div class="blue__selfdel">
                                    <img src="{% static 'icons/proc/purchase-cash-register-svgrepo-com%201.svg' %}" alt="purch" class="blue__img">
                                    <div class="blue__text">Самовывоз: сегодня</div>
                                </div>
                                <div class="blue__del">
                                    <img src="{% static 'icons/proc/delivery-shipping-and-delivery-svgrepo-com%202.svg' %}" alt="del" class="blue__img">
                                    <div class="blue__text">Доставка: завтра</div>
                                </div>
                                <div class="blue__buy">
                                    <div class="blue__price">{{ product.price }} ₸</div>
                                    <div class="blue__buttons">
                                        <button class="blue__oneclick">
                                            <img src="../../static/icons/proc/basket-commerce-and-shopping-svgrepo-com%201.svg" alt="one">
                                            <div class="button_text">В один клик</div>
                                        </button>
                                        <form action="{% url 'cart:add-to-cart' product.id %}" method="POST">
                                            {% csrf_token %}
                                            <button class="blue__basket">
                                                <img src="{% static 'icons/proc/cart-commerce-and-shopping-svgrepo-com%201%20(1).svg' %}" alt="cart">
                                                <div class="button__text">В коризну</div>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% empty %}
                            <h2 style="color: white">Нет товаров {{ brand_name }}</h2>
                        {% endfor %}

                        <div class="proc__links">

                            {% for page_num in page_range %}
                                {% if page_num == page_obj.number %}
                                    <span class="current">
                                        <div class="links__pagenmb">{{ page_num }}</div>
                                    </span>
                                {% else %}
                                    <a href="?page={{ page_num }}">
                                        <div class="links__pagenmb">{{ page_num }}</div>
                                    </a>
                                {% endif %}
                            {% endfor %}

                        </div>
                    </div>           
                </div>
            </div>
        </section>
{% endblock %}

store/templates/store/cart.html
{% extends 'store/base.html' %}
{% load custom_tags %}
{% block content %}
    <section class="basket">
        <div class="container">
            <h1>Моя корзина</h1>
            {% for cart_item in page_obj %}
                <div class="basket__el">
                    <div class="el__delete">
                        <form method="POST" action="{% url 'cart:cart-remove' cart_item.product.id %}">
                           {% csrf_token %}
                            <button><img src="../../static/icons/basket/basket-commerce-and-shopping-svgrepo-com%202.svg" alt="delete"></button>
                        </form>
                    </div>
                    <a href="{% url 'product' product_id=cart_item.product.id %}">
                    <div class="el__img"><img src="{{ cart_item.product.image.url }}" alt="img" style="width: 175px"></div>
                    <div class="el__descr">
                        <div class="el__name">{{ cart_item.product.name }}</div>
                        <div class="el__arc">Артикул: 000001</div>
                    </div>
                    </a>
                    <div class="el__plus">
                        <form action="{% url 'cart:cart-decrease' cart_item.product.id %}" method="POST">
                            {% csrf_token %}
                            <button class="el_minus">-</button>
                        </form>
                        <div class="el_value">{{ cart_item.quantity }}</div>
                        <form action="{% url 'cart:add-to-cart' cart_item.product.id %}" method="POST">
                            {% csrf_token %}
                            <button>+</button>
                        </form>
                    </div>
                    <div class="el__price">{{ cart_item.product.price|mul:cart_item.quantity }} ₸</div>
                </div>
            {% endfor %}

            

            <div class="basket__purchase">
                <div class="proc__links">

                    {% for page_num in page_range %}
                        {% if page_num == page_obj.number %}
                            <div class="links__pagenmb">{{ page_num }}</div>
                        {% else %}
                            <a href="?page={{ page_num }}">
                                <div class="links__pagenmb">{{ page_num }}</div>
                            </a>
                        {% endif %}
                    {% endfor %}

                </div>
                <div class="purchase__price">
                    <div class="purchase__text">Общая стоимость: {{ total_price }}</div>
                    <div class="purchase__exodus"></div>
                </div>
                <div class="purchase__button">
                    <a href="{% url 'cart:booking' %}"><button>Оформить заказ</button></a>
                </div>
            </div>
        </div>
    </section>

{% endblock %}


store/templates/store/favourites.html
{% extends 'store/base.html' %}
{% load static %}
{% block content %}
  <section class="chosen">
    <div class="container">
        <h1>Избранное</h1>
        {% for favourite_item in favourite_items %}
            <div class="chosen__wrapper">
                <div class="proc__goods">
                    <div class="goods__el">
                        <div class="goods__white">
                            <a href="product.html">
                                <div class="goods__img"><img src="{{ favourite_item.product.image.url }}" alt="proc" style="width: 200px"></div>
                                <div class="goods__descr">
                                    <div class="goods__name">{{ favourite_item.product.name }}</div>
                                    <div class="goods__wrapper">
                                        <div class="goods__param">
                                            <div class="param__type">
                                                <div class="param__cell">Тип процессора</div>
                                            </div>
                                            <div class="param__socket">
                                                <div class="param__cell">Сокет</div>
                                            </div>
                                            <div class="param__core">
                                                <div class="param__cell">Общее количество ядер</div>
                                            </div>
                                            <div class="param__stream">
                                                <div class="param__cell">Количество потоков</div>
                                            </div>
                                            <div class="param__frequency">
                                                <div class="param__cell">Тактовая частота, ГГц</div>
                                            </div>
                                            <div class="param__micro">
                                                <div class="param__cell">Микроархитектура</div>
                                            </div>
                                        </div>
                                        <div class="goods__data">
                                            {% for product_value in favourite_item.product.product_values.all%}
                                                    <div class="data__data">{{ product_value.value }}</div>
                                            {% endfor %}
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                        <div class="goods__blue">
                            <div class="blue__chosen">
                                <form method="POST" action="{% url 'cart:favourites-remove' favourite_item.product.id %}">
                                    {% csrf_token %}
                                    <button><img src="../../static/icons/chosen/Vector_3.svg" alt="like"></button>
                                </form>
                            </div>
                            <div class="blue__avail">
                                ✓  В наличии
                            </div>
                            <div class="blue__selfdel">
                                <img src="../../static/icons/proc/purchase-cash-register-svgrepo-com%201.svg" alt="purch" class="blue__img">
                                <div class="blue__text">Самовывоз: сегодня</div>
                            </div>
                            <div class="blue__del">
                                <img src="../../static/icons/proc/delivery-shipping-and-delivery-svgrepo-com%202.svg" alt="del" class="blue__img">
                                <div class="blue__text">Доставка: завтра</div>
                            </div>
                            <div class="blue__buy">
                                <div class="blue__price">{{ favourite_item.product.price }} ₸</div>
                                <div class="blue__buttons">
                                    <button class="blue__oneclick">
                                        <img src="../../static/icons/proc/basket-commerce-and-shopping-svgrepo-com%201.svg" alt="one">
                                        <div class="button_text">В один клик</div>
                                    </button>
                                    <form action="{% url 'cart:add-to-cart' favourite_item.product.id %}" method="post">
                                        {% csrf_token %}
                                        <button class="blue__basket">
                                            <img src="../../static/icons/proc/cart-commerce-and-shopping-svgrepo-com%201%20(1).svg" alt="cart">
                                            <div class="button__text">В коризну</div>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
  </section>

{% endblock %}

store/templates/store/login.html
{% extends "store/base.html" %}
{% load crispy_forms_tags %}
{% block title %}Log-in{% endblock %}


{% block content %}
<section class="enter">
        <div class="container">
            <div class="enter__flex">
                <form method="POST" action="{% url 'account:user-login' %}">
                    <div class="enter__h">Личный кабинет</div>
                    {% csrf_token %}

                    {{ form.username|as_crispy_field }}
                    <br>
                    {{ form.password|as_crispy_field }}
                    <br>
                    <div class="enter__wrapp">
                      <button>Забыли пароль ?</button>
                      <button><a href="{% url 'account:register' %}">Зарегистрироваться</a></button>
                    </div>
                    <br>
                    <button class="blue" type="submit">Войти</button>
                </form>

            </div>
        </div>
</section>
{% endblock %}